---
title: "Mini-Project 2"
author: "Sarah, Berry, Eva"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---


```{r, message=FALSE}
library(tidyverse)
library(dplyr)
library(ggrepel)
library(lubridate)
library(scales)
```

```{r, message=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
devtools::install_github("benmarwick/wordcountaddin")
```

> Word count: `r wordcountaddin::word_count()`

```{r, message=FALSE}

# Splits contributions into the date it occurred, transaction amount, and the the recipient's ID
ContributionsToEach <- contributions %>%
  select(transaction_dt, tran_id, transaction_amt, cand_id, name) %>%
# The date format was weird and ineffective so this splits it into 3 columns, for year, month, and day. I used "lubridate" which should be part of tidyverse
  mutate(FullDate = mdy(transaction_dt)) %>%
  separate(FullDate, sep="-", into = c("year", "month", "day"))

#add party variable
ContributionsToEach$party <- ifelse(ContributionsToEach$name == "MUNDY KATOWITZ MEDIA, INC.," | ContributionsToEach$name == "GMMB", 
c("Democrat"), c("Republican"))


#Can we filter out cancelled transactions by filtering out any observation that has a non-unique tran_id? Let's look at contributions for one candidate who had a lot of cancelled donations:
ContributionsToConyers <- ContributionsToEach %>% filter(cand_id == "H6MI01028")
#No - because cancellations receive a unique tran_id. Looking at this dataset, there are many cases where I can't figure out which positive transaction each negative one is cancelling, because there is nothing linking them.  

BigContributions2012 <- ContributionsToEach %>%
  filter(year == "2012") %>%
  filter(transaction_amt > 3000000) 
  
BigContributions2012$party <- ifelse(BigContributions2012$name == "MUNDY KATOWITZ MEDIA, INC.," | BigContributions2012$name == "GMMB", 
c("Democrat"), c("Republican"))
    

glimpse(BigContributions2012)
```

```{r, message=FALSE}
# everything
# I loaded the scales package, which should be in ggplot of tidyverse to make the transaction amount be in dollars and not exponents
ggplot(ContributionsToEach, aes(x = transaction_dt, y = transaction_amt, color = party)) + 
  scale_color_manual(values=c("#0000ff", "#ff0000")) +
  scale_y_continuous(labels = dollar) +
  geom_point() +
  labs(title = "Large Contributions in the 2012 Presidential Campaign", y = "transaction amount", x = "transaction date") +
scale_x_discrete(breaks = c(01012012, 02012012, 03012012, 04012012, 05012012, 06012012, 07012012, 08012012, 09012012, 10012012, 11012012, 12012012, 12312012),
  labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec", " ")) 
```


```{r, message=FALSE}

# just 2012 contributions on a log scale with text saying who donated each big donation.
# Democrat = MUNDY KATOWITZ MEDIA, GMMB, . Republican = MENTZER MEDIA SERVICES,CROSSROADS MEDIA, NATIONAL MEDIA RESEARCH PLANNING(?), AMERICAN RAMBLER PRODUCTIONS,

ggplot(BigContributions2012, aes(x = transaction_dt, y = transaction_amt, label = name, color = party)) +
  scale_color_manual(values=c("#0000ff", "#ff0000")) +
  scale_y_log10(labels = dollar) +
  geom_text_repel(size = 2) +
  geom_point(size = .5) +
  labs(title = "Top 50 Contributions to the 2012 Presidential Campaign", x = "transaction date", y = "transaction amount") +
  scale_x_discrete(breaks = c(01012012, 02012012, 03012012, 04012012, 05012012, 06012012, 07012012, 08012012, 09012012, 10012012, 11012012, 12012012),
  labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec")) 
```

```{r, message=FALSE}
# joining the tables (documentation; look for header of combine data sets at https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
# we care about how many contributions each candidate got. (or total money they got?)
# we will find the number of intances the candidate ID shows up
# count how many times the candidate ID appeared -> mutate that into a new collumn
# join that collumn (based on candiate ID) to the main "candidates" column
# in the end, we will have the original candidates spreadsheet and then two extra columns of number of individual contributions and total money donated to each candidate

# idk what I did but please please please don't delete "dplyr::" in these. It seems redundant but it's the only way it worked.

CandidatesProfile <- dplyr::left_join(candidates, contributions, by = "cand_id")

# is below countig the number of times a candidates name shows up?
CountNumberOfDonations <- CandidatesProfile %>%
  dplyr::group_by(cand_name) %>%
  dplyr::summarize(N = n())

BabyTable <- CandidatesProfile %>%
  dplyr::select(cand_id, cand_name, transaction_amt)

# make a list c(whatever names) from babytable
# I'm 50% sure that the code below produces a BIG list. 5524 house canidates seems about right

listOfCand <- BabyTable %>%
  dplyr::pull(cand_name)

listOfCand <- unique(listOfCand)

# sum up all teh donations for each name
# here's the start of my function but idk where to go from here.
# my goals are to 1) confirm it was a sucessful list 2) sum up the money per candidate using the list

MoneyPerCandidate <- function(cand_id) {
  Money <- BabyTable$cand_id
  Money
}

```


```{r, message=FALSE}

# just 2012 contributions on a log scale with text saying who donated each big donation.
# Democrat = MUNDY KATOWITZ MEDIA, GMMB, . Republican = MENTZER MEDIA SERVICES,CROSSROADS MEDIA, NATIONAL MEDIA RESEARCH PLANNING(?), AMERICAN RAMBLER PRODUCTIONS,

ggplot(BigContributions2012, aes(x = transaction_dt, y = transaction_amt, label = name, color = party)) +
  scale_color_manual(values=c("#0000ff", "#ff0000")) +
  scale_y_log10(labels = dollar) +
  geom_text(size = 2) +
  geom_point(size = .5) +
  labs(title = "Top 50 Contributions to the 2012 Presidential Campaign", x = "transaction date", y = "transaction amount") +
scale_x_discrete(breaks = c(01012012, 02012012, 03012012, 04012012, 05012012, 06012012, 07012012, 08012012, 09012012, 10012012, 11012012, 12012012),
  labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))

```

